services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: expensilo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: fastapi-backend
    restart: unless-stopped
    environment:
      SECRET_KEY: c3P2Vb8tF9Zs6Xk1Lq9D5yH4WnT0Qv6R
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 180
      DATABASE_URL: postgresql+psycopg2://postgres:1234@db:5432/expensilo
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
