services:
  - type: web
    name: fastapi-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: SECRET_KEY
        value: c3P2Vb8tF9Zs6Xk1Lq9D5yH4WnT0Qv6R
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "180"
      - key: DATABASE_URL
        value: postgresql://postgres:1234@postgres-db:5432/expensilo
    autoDeploy: true

  - type: pserv
    name: postgres-db
    env: docker
    dockerContext: .
    image: postgres:15
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: 1234
      - key: POSTGRES_DB
        value: expensilo
    disk:
      name: pgdata
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
